# Generated by Django 5.2.4 on 2025-07-19 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingrecord',
            old_name='entry_date',
            new_name='entry_time',
        ),
    ]
